# Meta-configuración del proveedor de JPA
provider.adapter.class=org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter
provider.dialect.key=hibernate.dialect

# Mapeo de Dialectos por SGBD
provider.dialect.sqlite=org.hibernate.community.dialect.SQLiteDialect
provider.dialect.mysql=org.hibernate.dialect.MySQLDialect
provider.dialect.mariadb=org.hibernate.dialect.MariaDBDialect
provider.dialect.postgresql=org.hibernate.dialect.PostgreSQLDialect
provider.dialect.oracle=org.hibernate.dialect.OracleDialect
provider.dialect.mssql=org.hibernate.dialect.SQLServerDialect
provider.dialect.h2=org.hibernate.dialect.H2Dialect

# Configuración del motor JPA
hibernate.hbm2ddl.auto=update
hibernate.show_sql=false
hibernate.format_sql=true
hibernate.use_sql_comments=true